name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        os-package-manager: [standard]
        include:
        - os: ubuntu-latest
          os-package-manager: [nix]
          python-version: '3.10'
        - os: macos-latest
          os-package-manager: [nix]
          python-version: '3.10'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v16
      if: matrix.os-package-manager == "nix"
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build
      if: matrix.os-package-manager == "nix"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade 'pip>=20.3'  # strict dependency resolution added in pip 20.3
        pip install -e '.[isort,test]'
    - name: Test with pytest
      run: |
        pytest
